version: '3.1'

services:
  db:
    image: postgres
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: example_user
      POSTGRES_PASSWORD: example_password
      POSTGRES_DB: example_db
    ports:
      - ${DB_PORT}:5432
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080